# Generated by Django 5.2.12 on 2026-03-06 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list, help_text='List of included features')),
                ('not_included', models.JSONField(blank=True, default=list, help_text='List of not included features')),
                ('icon', models.CharField(help_text='Path to icon or font class', max_length=100)),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+62 812-3456-7890', max_length=20)),
                ('address', models.TextField(default='Jl. Dusun Mlaten Gg. II, Gempol, Pasuruan, Jawa Timur')),
                ('email', models.EmailField(default='hello@angen2wedding.com', max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('mua', 'MUA'), ('decoration', 'Decoration'), ('tent', 'Tent'), ('catering', 'Catering'), ('photographer', 'Photographer'), ('music', 'Music'), ('invitation', 'Invitation'), ('gift', 'Gift')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_range', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendors/')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=20)),
                ('event_date', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('guest_count', models.CharField(max_length=50)),
                ('add_ons', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('booking', 'Booking'), ('dp', 'Down Payment'), ('technical_meeting', 'Technical Meeting'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booking', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.package')),
            ],
        ),
    ]
